/// <reference path="../../src/bobril.d.ts"/>
/// <reference path="./components.ts"/>


var header = ["Firstname", "Lastname", "E-mail", "Date of birth"];
var body = [
    [
        "Harper",
        "Skinner",
        "Suspendisse.aliquet.sem@enimnislelementum.com",
        "12/Dec/1414"
    ],
    [
        "Nolan",
        "Bender",
        "dui.nec.tempus@fringillacursuspurus.com",
        "12/May/1616"
    ],
    [
        "Elijah",
        "Haynes",
        "ullamcorper@egetvolutpat.org",
        "08/May/1414"
    ],
    [
        "Jeremy",
        "Maldonado",
        "Nulla@parturientmontesnascetur.org",
        "30/Jul/1414"
    ],
    [
        "Wade",
        "Wyatt",
        "Sed.auctor@maurisipsum.com",
        "20/Jul/1515"
    ],
    [
        "Kevin",
        "Coleman",
        "dolor.elit@libero.net",
        "18/Nov/1414"
    ],
    [
        "Ali",
        "Miller",
        "id@ipsum.edu",
        "16/Jul/1515"
    ],
    [
        "Kieran",
        "Brennan",
        "adipiscing@Nuncullamcorper.org",
        "21/Jul/1515"
    ],
    [
        "Blake",
        "Page",
        "venenatis@luctuset.co.uk",
        "22/Apr/1515"
    ],
    [
        "Dorian",
        "Avery",
        "primis@miacmattis.net",
        "28/Feb/1616"
    ],
    [
        "Ishmael",
        "Wooten",
        "in.aliquet@risusDonec.com",
        "15/Apr/1515"
    ],
    [
        "Aristotle",
        "Clark",
        "odio@dapibus.co.uk",
        "07/Mar/1515"
    ],
    [
        "Ivan",
        "Mejia",
        "massa.Mauris@enimSuspendisse.edu",
        "13/Jul/1414"
    ],
    [
        "Wyatt",
        "Lancaster",
        "lacinia.at@Etiamlaoreetlibero.co.uk",
        "27/Feb/1616"
    ],
    [
        "Dalton",
        "Randall",
        "rhoncus.Nullam.velit@quamquis.co.uk",
        "18/Apr/1616"
    ],
    [
        "Porter",
        "Valenzuela",
        "Suspendisse.aliquet.molestie@fermentumfermentumarcu.org",
        "05/Jan/1616"
    ],
    [
        "Thor",
        "Stephens",
        "a.nunc.In@Nam.ca",
        "29/Sep/1515"
    ],
    [
        "Alan",
        "Rowe",
        "tristique.pellentesque@Donecest.com",
        "04/Jan/1616"
    ],
    [
        "Francis",
        "Mccullough",
        "nec@Morbi.net",
        "07/May/1515"
    ],
    [
        "Hector",
        "Holcomb",
        "tristique.pellentesque.tellus@rutrumeuultrices.com",
        "18/Sep/1515"
    ],
    [
        "Aladdin",
        "Foreman",
        "ultrices.Duis@aliquetnecimperdiet.net",
        "25/Jan/1616"
    ],
    [
        "Gil",
        "Solomon",
        "vitae.mauris@egestas.org",
        "22/Jul/1414"
    ],
    [
        "Brennan",
        "Carver",
        "tincidunt.pede@Etiam.co.uk",
        "17/Feb/1515"
    ],
    [
        "Wing",
        "Strickland",
        "cursus.vestibulum@aneque.net",
        "26/Jul/1515"
    ],
    [
        "Brock",
        "Terry",
        "vitae.sodales.nisi@Donectempuslorem.com",
        "04/Feb/1515"
    ],
    [
        "Bernard",
        "Aguirre",
        "Aliquam@vel.edu",
        "24/Apr/1616"
    ],
    [
        "Gary",
        "Cervantes",
        "elit.erat@leoMorbineque.co.uk",
        "23/Oct/1515"
    ],
    [
        "Marshall",
        "Coleman",
        "dictum.ultricies.ligula@nisiMauris.edu",
        "05/Aug/1515"
    ],
    [
        "Ferdinand",
        "Kemp",
        "mauris@Nullatempor.co.uk",
        "07/Jun/1515"
    ],
    [
        "Bert",
        "Franklin",
        "ullamcorper.Duis@tortor.org",
        "26/Sep/1515"
    ],
    [
        "Michael",
        "Conway",
        "quis@rhoncusid.edu",
        "16/Feb/1515"
    ],
    [
        "Austin",
        "Castillo",
        "Fusce.dolor@urnaconvalliserat.net",
        "01/May/1414"
    ],
    [
        "Hu",
        "Molina",
        "ante.Maecenas.mi@orcisemeget.edu",
        "24/Mar/1515"
    ],
    [
        "Davis",
        "Conner",
        "amet@vitae.co.uk",
        "18/Aug/1515"
    ],
    [
        "Driscoll",
        "Lambert",
        "eu.arcu.Morbi@Fusce.co.uk",
        "11/Mar/1616"
    ],
    [
        "Dexter",
        "Mercado",
        "litora.torquent.per@idlibero.com",
        "18/Jun/1414"
    ],
    [
        "Hakeem",
        "Mitchell",
        "scelerisque.scelerisque@semelitpharetra.co.uk",
        "18/Oct/1414"
    ],
    [
        "Griffin",
        "Shaw",
        "et.netus.et@facilisisloremtristique.ca",
        "09/Jul/1414"
    ],
    [
        "Lester",
        "Peterson",
        "auctor@lorem.co.uk",
        "21/Mar/1616"
    ],
    [
        "Grant",
        "Little",
        "lectus@tempuslorem.co.uk",
        "24/Jul/1414"
    ],
    [
        "Warren",
        "Goff",
        "pede.sagittis@nibhAliquam.com",
        "05/Jan/1616"
    ],
    [
        "Wayne",
        "Suarez",
        "Quisque.varius@Duiscursus.edu",
        "28/Apr/1515"
    ],
    [
        "Ishmael",
        "Mcneil",
        "tellus.Nunc@Donecvitae.edu",
        "31/Dec/1515"
    ],
    [
        "Burton",
        "Bowen",
        "semper.cursus@ametrisusDonec.com",
        "27/Mar/1616"
    ],
    [
        "Aidan",
        "Medina",
        "aliquam.eu.accumsan@variusultrices.edu",
        "06/Oct/1515"
    ],
    [
        "Reese",
        "Forbes",
        "Proin.non.massa@amet.com",
        "29/Jul/1515"
    ],
    [
        "Tanek",
        "Mcfarland",
        "non.enim@odioEtiam.net",
        "31/Jan/1616"
    ],
    [
        "Vernon",
        "Hewitt",
        "sem.vitae.aliquam@magnisdis.org",
        "19/Oct/1414"
    ],
    [
        "Conan",
        "Oliver",
        "Maecenas.libero@nibh.com",
        "25/Sep/1414"
    ],
    [
        "Xanthus",
        "Davis",
        "Lorem.ipsum@tinciduntaliquam.org",
        "11/Jul/1515"
    ],
    [
        "Isaac",
        "Chavez",
        "vitae.semper@fringilla.co.uk",
        "08/Dec/1515"
    ],
    [
        "Thaddeus",
        "Benton",
        "aliquam.adipiscing.lacus@et.edu",
        "13/Jul/1515"
    ],
    [
        "Edward",
        "Webster",
        "ac.nulla.In@aauctornon.edu",
        "10/Feb/1515"
    ],
    [
        "Declan",
        "Pratt",
        "eu@Crasdolor.com",
        "13/Nov/1515"
    ],
    [
        "Calvin",
        "Velazquez",
        "et.commodo.at@suscipit.ca",
        "28/May/1515"
    ],
    [
        "Rigel",
        "Andrews",
        "vel.est@auctornon.ca",
        "21/Aug/1515"
    ],
    [
        "Kareem",
        "Tyler",
        "Sed@Proin.ca",
        "07/Oct/1515"
    ],
    [
        "Orson",
        "Cox",
        "Donec.luctus@maurisaliquameu.ca",
        "13/Apr/1515"
    ],
    [
        "Mannix",
        "Bryant",
        "rutrum.justo@pharetraut.net",
        "29/May/1515"
    ],
    [
        "Allistair",
        "Sims",
        "ante.bibendum.ullamcorper@Nuncullamcorper.net",
        "28/Jul/1414"
    ],
    [
        "Dane",
        "Carroll",
        "Quisque.tincidunt@NullainterdumCurabitur.edu",
        "08/Jul/1414"
    ],
    [
        "Avram",
        "Goodwin",
        "eget.metus.eu@cursus.edu",
        "28/Nov/1414"
    ],
    [
        "Melvin",
        "Chaney",
        "Fusce.dolor.quam@pedeCrasvulputate.edu",
        "28/Mar/1515"
    ],
    [
        "Noble",
        "Garner",
        "eget.odio@Cras.net",
        "30/Jul/1414"
    ],
    [
        "Colt",
        "Shields",
        "tellus@eleifendnec.co.uk",
        "29/Nov/1414"
    ],
    [
        "Troy",
        "Castillo",
        "hendrerit.id.ante@adipiscingelitEtiam.net",
        "09/Sep/1414"
    ],
    [
        "Jelani",
        "Santiago",
        "Integer@faucibusut.com",
        "23/Mar/1616"
    ],
    [
        "Lance",
        "Odonnell",
        "libero@estNunc.org",
        "16/Nov/1414"
    ],
    [
        "Kaseem",
        "Hale",
        "non@gravidanuncsed.co.uk",
        "14/Jun/1414"
    ],
    [
        "Ezra",
        "Woodard",
        "cubilia.Curae.Phasellus@nibh.ca",
        "04/Sep/1414"
    ],
    [
        "Jonas",
        "Palmer",
        "lorem.lorem.luctus@consectetuer.net",
        "09/May/1616"
    ],
    [
        "Rahim",
        "Walters",
        "lectus.Nullam.suscipit@Fusce.org",
        "02/Nov/1515"
    ],
    [
        "Lars",
        "Holloway",
        "magna@ante.edu",
        "14/Oct/1414"
    ],
    [
        "Uriel",
        "Roman",
        "metus@lectusquismassa.net",
        "05/May/1616"
    ],
    [
        "Raymond",
        "Tate",
        "luctus.et@dolortempus.org",
        "09/Feb/1515"
    ],
    [
        "Bruno",
        "Davis",
        "nonummy@egestasligulaNullam.com",
        "29/Nov/1414"
    ],
    [
        "Roth",
        "Black",
        "nulla@mattis.edu",
        "12/Jul/1515"
    ],
    [
        "Clarke",
        "Tanner",
        "nibh.lacinia.orci@ut.com",
        "17/Jan/1616"
    ],
    [
        "Lionel",
        "Norris",
        "quis@vulputateullamcorper.org",
        "13/Oct/1515"
    ],
    [
        "Calvin",
        "Richard",
        "pede.et.risus@feugiatSednec.com",
        "22/Jun/1515"
    ],
    [
        "Allen",
        "Munoz",
        "quis@amifringilla.net",
        "16/Feb/1616"
    ],
    [
        "Lars",
        "Gross",
        "Integer@massaVestibulum.net",
        "15/Sep/1414"
    ],
    [
        "Guy",
        "Rodriguez",
        "Aliquam@purusaccumsaninterdum.org",
        "26/Oct/1414"
    ],
    [
        "Nicholas",
        "Henry",
        "Duis.gravida.Praesent@lacus.ca",
        "15/Nov/1515"
    ],
    [
        "Louis",
        "Ochoa",
        "vitae@urnanecluctus.com",
        "25/Apr/1616"
    ],
    [
        "Lance",
        "Hogan",
        "ullamcorper.eu.euismod@at.net",
        "06/Oct/1515"
    ],
    [
        "Ethan",
        "Velazquez",
        "nec@facilisisegetipsum.co.uk",
        "24/Jun/1515"
    ],
    [
        "Perry",
        "Gallagher",
        "rutrum.justo@vulputate.net",
        "24/May/1515"
    ],
    [
        "Nicholas",
        "Gaines",
        "montes.nascetur.ridiculus@Proinvel.net",
        "10/Feb/1515"
    ],
    [
        "Levi",
        "Watts",
        "aliquet@augue.co.uk",
        "03/Feb/1616"
    ],
    [
        "Elliott",
        "Freeman",
        "sem@non.com",
        "03/Nov/1515"
    ],
    [
        "Malik",
        "Rivera",
        "ante.blandit@metusAenean.com",
        "26/Mar/1515"
    ],
    [
        "Ahmed",
        "Wiggins",
        "quam@Pellentesqueut.com",
        "26/Nov/1414"
    ],
    [
        "Driscoll",
        "Martinez",
        "nisl@nunc.edu",
        "19/Jan/1515"
    ],
    [
        "Porter",
        "Matthews",
        "ac.facilisis.facilisis@etmagna.ca",
        "19/Jul/1414"
    ],
    [
        "Kevin",
        "Ellis",
        "amet.consectetuer.adipiscing@id.org",
        "18/Jul/1515"
    ],
    [
        "Moses",
        "Santiago",
        "a.tortor.Nunc@nonummyultriciesornare.co.uk",
        "14/Oct/1515"
    ],
    [
        "Reese",
        "Hines",
        "sem.magna.nec@Maecenas.ca",
        "11/Nov/1515"
    ],
    [
        "Peter",
        "Cardenas",
        "nec.quam@enim.co.uk",
        "30/Oct/1515"
    ],
    [
        "Jelani",
        "Zamora",
        "luctus@mollis.org",
        "21/Jul/1414"
    ]
];

module DynamicDataTableApp {

    var dynamicDataTable = new DynamicDataTableApp.DynamicDatatableModel(header, body, 10);

    b.init(() => {
        return { component: DynamicDataTableApp.App, data: { tableModel: dynamicDataTable } };
    });
}
